#!/bin/bash
#SBATCH --job-name=_192_32_
#SBATCH -D ./
#SBATCH --ntasks=1
#SBATCH --output=benchmarks/lora/definitive_results/finding_maximum/check_available_gpu_memory/llama-3.1-8b-instruct/_192_32_/log_%j.out
#SBATCH --error=benchmarks/lora/definitive_results/finding_maximum/check_available_gpu_memory/llama-3.1-8b-instruct/_192_32_/log_%j.err
#SBATCH --cpus-per-task=20
#SBATCH --gres gpu:1
#SBATCH --time=00:25:00
module load singularity
singularity exec --nv  --env PYTHONPATH=/usr/local/lib/python3.12/dist-packages --env TOKENIZERS_PARALLELISM=false --env VLLM_CACHE_ROOT=/scratch/tmp/_192_32__522890463 --bind /gpfs/home/bsc/bsc098069/llm_benchmarking/vLLMAdapterServingScaling/vllm/core:/usr/local/lib/python3.12/dist-packages/vllm/core --bind /gpfs/home/bsc/bsc098069/llm_benchmarking/vLLMAdapterServingScaling/vllm/engine:/usr/local/lib/python3.12/dist-packages/vllm/engine --bind /gpfs/home/bsc/bsc098069/llm_benchmarking/vLLMAdapterServingScaling/vllm/entrypoints:/usr/local/lib/python3.12/dist-packages/vllm/entrypoints --bind /gpfs/home/bsc/bsc098069/llm_benchmarking/vLLMAdapterServingScaling/vllm/executor:/usr/local/lib/python3.12/dist-packages/vllm/executor --bind /gpfs/home/bsc/bsc098069/llm_benchmarking/vLLMAdapterServingScaling/vllm/lora:/usr/local/lib/python3.12/dist-packages/vllm/lora --bind /gpfs/home/bsc/bsc098069/llm_benchmarking/vLLMAdapterServingScaling/vllm/model_executor:/usr/local/lib/python3.12/dist-packages/vllm/model_executor --bind /gpfs/home/bsc/bsc098069/llm_benchmarking/vLLMAdapterServingScaling/vllm/worker:/usr/local/lib/python3.12/dist-packages/vllm/worker --bind /gpfs/home/bsc/bsc098069/llm_benchmarking/vLLMAdapterServingScaling/vllm/config.py:/usr/local/lib/python3.12/dist-packages/vllm/config.py --bind /gpfs/home/bsc/bsc098069/llm_benchmarking/vLLMAdapterServingScaling/vllm/sequence.py:/usr/local/lib/python3.12/dist-packages/vllm/sequence.py --bind /gpfs/home/bsc/bsc098069/llm_benchmarking/vLLMAdapterServingScaling/vllm/outputs.py:/usr/local/lib/python3.12/dist-packages/vllm/outputs.py --bind /gpfs/home/bsc/bsc098069/llm_benchmarking/vLLMAdapterServingScaling/vllm/v1/core:/usr/local/lib/python3.12/dist-packages/vllm/v1/core /gpfs/scratch/bsc98/bsc098069/llm_benchmarking/images/vllm_0.8.5.sif python3 benchmarks/lora/benchmark_serving.py --port='23652' --result-dir='benchmarks/lora/definitive_results/finding_maximum/check_available_gpu_memory/llama-3.1-8b-instruct/_192_32_' --disable-log-stats --disable-loras-users --disable-tqdm --backend='openai' --dataset-path='/gpfs/scratch/bsc98/bsc098069/llm_benchmarking/data/ShareGPT_V3_unfiltered_cleaned_split.json' --endpoint='/v1/completions' --model='/gpfs/scratch/bsc98/bsc098069/llm_benchmarking/models/llama/llama-3.1-8b-instruct' --save-result --num-prompts='1' --server-init-time='1800' --launch-server --server-args='--port=23652 --disable-log-stats --disable-log-requests --model="/gpfs/scratch/bsc98/bsc098069/llm_benchmarking/models/llama/llama-3.1-8b-instruct" --enable-lora --max-num-seqs="2048" --scheduler-cls="vllm.v1.core.sched.scheduler.Scheduler" --no-enable-prefix-caching --max-loras='192' --max-lora-rank='32''