#!/bin/bash
#SBATCH --job-name=_600__100_400
#SBATCH -D ./
#SBATCH --ntasks=1
#SBATCH --output=digital_twin_dynamic/estimators/predictor_default_latency/qwen-2.5-7b-instruct/grouped_per_step/_600__100_400/log_%j.out
#SBATCH --error=digital_twin_dynamic/estimators/predictor_default_latency/qwen-2.5-7b-instruct/grouped_per_step/_600__100_400/log_%j.err
#SBATCH --cpus-per-task=20
#SBATCH --gres gpu:1
#SBATCH --time=00:35:00
module load singularity
singularity exec --nv  --env PYTHONPATH=/usr/local/lib/python3.12/dist-packages --env TOKENIZERS_PARALLELISM=false --env VLLM_CACHE_ROOT=/scratch/tmp/_600__100_400_958916617 --bind /gpfs/home/bsc/bsc098069/llm_benchmarking/vLLMAdapterServingScaling/vllm/core:/usr/local/lib/python3.12/dist-packages/vllm/core --bind /gpfs/home/bsc/bsc098069/llm_benchmarking/vLLMAdapterServingScaling/vllm/engine:/usr/local/lib/python3.12/dist-packages/vllm/engine --bind /gpfs/home/bsc/bsc098069/llm_benchmarking/vLLMAdapterServingScaling/vllm/entrypoints:/usr/local/lib/python3.12/dist-packages/vllm/entrypoints --bind /gpfs/home/bsc/bsc098069/llm_benchmarking/vLLMAdapterServingScaling/vllm/executor:/usr/local/lib/python3.12/dist-packages/vllm/executor --bind /gpfs/home/bsc/bsc098069/llm_benchmarking/vLLMAdapterServingScaling/vllm/lora:/usr/local/lib/python3.12/dist-packages/vllm/lora --bind /gpfs/home/bsc/bsc098069/llm_benchmarking/vLLMAdapterServingScaling/vllm/model_executor:/usr/local/lib/python3.12/dist-packages/vllm/model_executor --bind /gpfs/home/bsc/bsc098069/llm_benchmarking/vLLMAdapterServingScaling/vllm/worker:/usr/local/lib/python3.12/dist-packages/vllm/worker --bind /gpfs/home/bsc/bsc098069/llm_benchmarking/vLLMAdapterServingScaling/vllm/config.py:/usr/local/lib/python3.12/dist-packages/vllm/config.py --bind /gpfs/home/bsc/bsc098069/llm_benchmarking/vLLMAdapterServingScaling/vllm/sequence.py:/usr/local/lib/python3.12/dist-packages/vllm/sequence.py --bind /gpfs/home/bsc/bsc098069/llm_benchmarking/vLLMAdapterServingScaling/vllm/outputs.py:/usr/local/lib/python3.12/dist-packages/vllm/outputs.py --bind /gpfs/home/bsc/bsc098069/llm_benchmarking/vLLMAdapterServingScaling/vllm/v1/core:/usr/local/lib/python3.12/dist-packages/vllm/v1/core /gpfs/scratch/bsc98/bsc098069/llm_benchmarking/images/vllm_0.8.5.sif python3 benchmarks/lora/benchmark_serving.py --port='45390' --result-dir='digital_twin_dynamic/estimators/predictor_default_latency/qwen-2.5-7b-instruct/grouped_per_step/_600__100_400' --disable-loras-users --backend='openai' --disable-tqdm --use-synthetic-dataset='/gpfs/scratch/bsc98/bsc098069/llm_benchmarking/data/common_american_words.txt' --endpoint='/v1/completions' --model='/gpfs/scratch/bsc98/bsc098069/llm_benchmarking/models/qwen/qwen-2.5-7b-instruct' --num-prompts='8192' --save-result --synthetic-input-length='100' --synthetic-output-length='400' --launch-server --server-args='--port=45390 --disable-log-requests --model="/gpfs/scratch/bsc98/bsc098069/llm_benchmarking/models/qwen/qwen-2.5-7b-instruct" --scheduler-cls="vllm.v1.core.sched.scheduler.Scheduler" --no-enable-prefix-caching --max-num-seqs='600''